env='develop'
hashed_text='5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9'

[notion_service]
access_token=''
database_id=''

[notion_pinterest_service]
access_token=''
database_id=''

[aws_service]
access_key_id=''
secret_access_key=''
region_name=''

[hugging_face_service]
access_token=''

[google_custom_search_api]
cx=''
key=''